"""
Django settings for mywebsite project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import datetime

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8z-u_3qx5w%miivo)cocpa2k(x3brivzw@^5xw^z@fnx!###dx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

TELEGRAM_BOT_TOKEN = '6659966867:AAGNLKtSJbpN23Is27BXSegu9_KWYygMpH4'

ALLOWED_HOSTS = ['www.account.trader-vibes.com', 'account.trader-vibes.com']

SESSION_COOKIE_AGE = 86400  # Waktu kadaluwarsa sesi dalam detik
# SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Sesuaikan sesuai kebutuhan

RECAPTCHA_PUBLIC_KEY = '6LfyHIkoAAAAAC9dapBXRQ1ZerJE6Y2A5GvPAA5N'
RECAPTCHA_PRIVATE_KEY = '6LfyHIkoAAAAAFIDhOVjy2hcOddcMW-N2jQpbn3t'
# RECAPTCHA_PROXY = 'http://your_proxy/'  # Opsional


SITE_ID = 2

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dashboard',
    'profileApp',
    'settingsApp',
    'tablesApp',
    'event',
    'copytrade',
    'video_learning',
    'productapp',
    'articelApp',
    'ckeditor',
    'captcha',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'METHOD': 'oauth2',
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'articelApp.middleware.ViewerMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'mywebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mywebsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = '/home/n1566869/public_html/account.trader-vibes.com/static/'
MEDIA_URL = '/media/'  # URL yang digunakan untuk mengakses file media
MEDIA_ROOT = '/home/n1566869/public_html/account.trader-vibes.com/media/'  # Menyimpan file media di direktori 'media' di dalam proyek
STATICFILES_DIRS  = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Emailing settings
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_FROM = 'j.riswan321@gmail.com'
# EMAIL_HOST_PASSWORD = 'bupoowasxicefcdg'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True  # Menggunakan TLS
# EMAIL_USE_SSL = True  # Atau, gunakan ini jika Anda ingin menggunakan SSL
EMAIL_HOST_USER = 'info.tradervibes@gmail.com'  # Ganti dengan alamat email Anda
EMAIL_HOST_PASSWORD = 'iiwwpiccepemspah'  # Ganti dengan kata sandi email Anda atau kata sandi aplikasi

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'mail.trader-vibes.com'
# EMAIL_PORT = 465
# EMAIL_USE_SSL = True
# EMAIL_HOST_USER = 'info@trader-vibes.com'
# EMAIL_HOST_PASSWORD = 'Mars012023'  # Ganti dengan kata sandi email atau kata sandi aplikasi


PASSWORD_RESET_TIMEOUT = 14400

SOCIALACCOUNT_LOGIN_ON_GET=True

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

AUTHENTICATION_CLASSES = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'allauth.socialaccount.providers.oauth2.auth.OAuth2LoginView',
)

LOGIN_URL = 'login'  # Ganti dengan URL halaman login kustom Anda
LOGIN_REDIRECT_URL = 'login'  # Ganti dengan URL halaman login kustom Anda
LOGOUT_REDIRECT_URL = 'login'  # Ganti dengan URL halaman login kustom Anda