# Generated by Django 4.2.4 on 2023-08-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_image_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.CharField(default='Fauzi Fibox', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
