# Generated by Django 4.2.4 on 2023-09-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_events_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('speaker', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='event_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
