# Generated by Django 4.2.4 on 2023-09-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0006_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('mql4', 'MQL4'), ('mql5', 'MQL5'), ('book', 'BOOK')], default='mql4', max_length=4),
        ),
    ]
