# Generated by Django 4.2.4 on 2023-10-05 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0007_alter_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MT4MT5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt_name', models.CharField(max_length=100)),
                ('token', models.CharField(blank=True, editable=False, max_length=64)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productapp.product')),
            ],
        ),
    ]
