# Generated by Django 4.2.4 on 2023-10-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0008_mt4mt5'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='mt_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.DeleteModel(
            name='MT4MT5',
        ),
    ]
