# Generated by Django 4.2.4 on 2023-10-05 09:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0009_purchase_mt_name_purchase_token_delete_mt4mt5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
