# Generated by Django 4.2.4 on 2023-09-12 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('copytrade', '0003_alter_copytrade_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerCopyTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MasterCopyTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=50)),
                ('port', models.CharField(max_length=10)),
                ('token', models.CharField(blank=True, max_length=100)),
                ('foto', models.ImageField(upload_to='master_photos')),
                ('deskripsi', models.TextField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='metatraders',
            name='user',
        ),
        migrations.DeleteModel(
            name='CopyTrade',
        ),
        migrations.DeleteModel(
            name='Metatraders',
        ),
        migrations.AddField(
            model_name='followercopytrade',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copytrade.mastercopytrade'),
        ),
        migrations.AddField(
            model_name='followercopytrade',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
