# Generated by Django 4.2.4 on 2023-09-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrade', '0004_followercopytrade_mastercopytrade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercopytrade',
            name='harga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
