# Generated by Django 4.2.4 on 2023-09-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrade', '0005_alter_mastercopytrade_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercopytrade',
            name='harga',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
