# Generated by Django 4.2.4 on 2023-08-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qn_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
    ]
