# Generated by Django 4.2.4 on 2023-08-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qn_settings', '0003_alter_account_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
