# Generated by Django 4.2.4 on 2023-08-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qn_settings', '0004_alter_account_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
    ]
