# Generated by Django 4.2.4 on 2023-08-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qn_settings', '0005_remove_account_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_bio',
            field=models.CharField(blank=True, default='Write Your Bio...', max_length=100, null=True),
        ),
    ]
