# Generated by Django 4.2.4 on 2023-08-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qn_settings', '0006_alter_account_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
