# Generated by Django 4.2.4 on 2023-08-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qn_settings', '0009_rename_profile_image_account_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='iamge',
            new_name='profile_image',
        ),
    ]
