# Generated by Django 4.2.4 on 2023-08-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qn_settings', '0011_remove_account_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
